"""End-to-end tests of canon_sync.py against the markdown sample in templates/."""

from __future__ import annotations

import json
import re
from pathlib import Path

SLUGS = [
    "company_readme",
    "positioning",
    "messaging",
    "sales_storyboard",
    "icp_personas",
    "competitive_battlecards",
    "glossary",
    "brand_voice",
    "operating_rules",
]

META_KEYS = {
    "generated_at",
    "last_synced_at",
    "contract_version",
    "source_of_truth",
    "pages_synced",
    "pages_missing",
    "bundle_bytes",
    "validation",
    "warnings",
    "content_hash",
}

PAGE_KEYS = {"title", "status", "owner", "review", "url", "available", "markdown"}

# The header from docs/formats.md section 5, line by line.
HEADER_RE = re.compile(
    r"\A<!-- generated by canon-sync\. DO NOT EDIT: edit the source page, the next sync overwrites this file\.\n"
    r"source: (?P<url>\S+) \| slug: (?P<slug>[a-z_]+) \| status: (?P<status>grounded|draft|stub|deprecated) \| owner: (?P<owner>[^\n|]+)\n"
    r"generated_at: (?P<generated_at>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z) \| caveat: (?P<caveat>[^\n|]+?)(?P<avail> \| available: false)? -->\n"
)

T1 = "2026-10-08T02:00:00Z"
T2 = "2026-10-09T02:00:00Z"
T3 = "2026-10-10T02:00:00Z"


def read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def test_sample_sync_writes_every_artifact(workspace: Path, run_sync):
    result = run_sync("--now", T1)
    assert result.returncode == 0, result.stdout + result.stderr

    export = workspace / "export"
    canon_files = sorted(path.name for path in (export / "canon").glob("*.md"))
    assert canon_files == sorted(f"{slug}.md" for slug in SLUGS)

    # contract.yaml is a verbatim copy of the source bytes.
    source = (workspace / "templates/contracts/context-contract.yaml").read_bytes()
    assert (export / "contract.yaml").read_bytes() == source

    # Every page file starts with the exact header shape and carries its frontmatter.
    for slug in SLUGS:
        text = (export / "canon" / f"{slug}.md").read_text(encoding="utf-8")
        match = HEADER_RE.match(text)
        assert match, f"{slug}: header does not match the spec shape:\n{text[:300]}"
        assert match.group("slug") == slug
        assert match.group("generated_at") == T1
        assert match.group("avail") is None
        assert text[match.end():].startswith("---\n"), f"{slug}: frontmatter should follow the header"

    meta = read_json(export / "meta.json")
    assert set(meta) == META_KEYS
    assert meta["generated_at"] == T1 and meta["last_synced_at"] == T1
    assert meta["pages_synced"] == SLUGS
    assert meta["pages_missing"] == []
    assert meta["validation"] == "passed"
    assert meta["warnings"] == []
    assert meta["source_of_truth"] == "markdown"
    assert meta["contract_version"] == 2
    assert meta["bundle_bytes"] == (export / "bundle.json").stat().st_size

    bundle = read_json(export / "bundle.json")
    assert {"generated_at", "contract", "pages"} <= set(bundle)
    assert bundle["generated_at"] == T1
    assert bundle["contract"]["canonical_pages"].keys() == set(SLUGS)
    assert bundle["contract"]["last_reviewed"] == "2026-10-08"  # dates serialised as strings
    assert list(bundle["pages"]) == SLUGS
    for slug, page in bundle["pages"].items():
        assert PAGE_KEYS <= set(page), slug
        assert page["available"] is True
        assert page["markdown"] == (export / "canon" / f"{slug}.md").read_text(encoding="utf-8")
        assert page["url"].endswith(f"/{slug}.md")
    assert bundle["pages"]["operating_rules"]["owner"] == "agent_operator"
    assert bundle["pages"]["glossary"]["status"] == "draft"

    # The summary names both clocks.
    assert "generated_at" in result.stdout and "last_synced_at" in result.stdout
    assert "9 page(s) synced" in result.stdout


def test_missing_page_becomes_placeholder(workspace: Path, run_sync):
    (workspace / "templates/canon/brand_voice.md").unlink()
    result = run_sync("--now", T1)
    assert result.returncode == 0, result.stdout + result.stderr

    export = workspace / "export"
    placeholder = (export / "canon/brand_voice.md").read_text(encoding="utf-8")
    match = HEADER_RE.match(placeholder)
    assert match and match.group("avail") == " | available: false"
    assert placeholder == match.group(0), "placeholder body must be empty"

    meta = read_json(export / "meta.json")
    assert meta["pages_missing"] == ["brand_voice"]
    assert "brand_voice" not in meta["pages_synced"]
    assert any("brand_voice" in warning for warning in meta["warnings"])

    page = read_json(export / "bundle.json")["pages"]["brand_voice"]
    assert page["available"] is False and page["markdown"] == ""

    # A missing page is a warning, so --fail-on-warn turns it into a failure.
    assert run_sync("--now", T1, "--fail-on-warn").returncode == 1


def test_grounded_page_with_marker_fails_and_writes_nothing(workspace: Path, run_sync):
    page = workspace / "templates/canon/messaging.md"  # grounded in the contract
    page.write_text(page.read_text(encoding="utf-8") + "\n- [CONFIRM] the pillar wording with PMM.\n", encoding="utf-8")
    result = run_sync("--now", T1)
    assert result.returncode == 1
    assert "messaging" in result.stderr and "[CONFIRM]" in result.stderr
    assert not (workspace / "export").exists(), "a failed run must not write anything"

    # [YOU DECIDE] is blocked the same way.
    page.write_text(page.read_text(encoding="utf-8").replace("[CONFIRM]", "[YOU DECIDE]"), encoding="utf-8")
    result = run_sync("--now", T1)
    assert result.returncode == 1 and "[YOU DECIDE]" in result.stderr


def test_frontmatter_disagreeing_with_contract_fails(workspace: Path, run_sync):
    page = workspace / "templates/canon/company_readme.md"
    page.write_text(page.read_text(encoding="utf-8").replace("status: grounded", "status: draft", 1), encoding="utf-8")
    result = run_sync("--now", T1)
    assert result.returncode == 1
    assert "company_readme" in result.stderr and "status" in result.stderr


def test_two_clocks(workspace: Path, run_sync):
    assert run_sync("--now", T1).returncode == 0
    meta = read_json(workspace / "export/meta.json")
    assert meta["generated_at"] == T1 and meta["last_synced_at"] == T1
    bundle_before = (workspace / "export/bundle.json").read_bytes()
    header_before = (workspace / "export/canon/positioning.md").read_text(encoding="utf-8").splitlines()[2]

    # Second run, nothing changed: heartbeat advances, generated_at does not.
    result = run_sync("--now", T2)
    assert result.returncode == 0, result.stdout + result.stderr
    meta = read_json(workspace / "export/meta.json")
    assert meta["generated_at"] == T1
    assert meta["last_synced_at"] == T2
    assert (workspace / "export/bundle.json").read_bytes() == bundle_before, "unchanged content keeps bundle.json byte-identical"
    assert (workspace / "export/canon/positioning.md").read_text(encoding="utf-8").splitlines()[2] == header_before
    assert "kept generated_at" in result.stdout

    # Third run after an edit: both clocks move.
    page = workspace / "templates/canon/positioning.md"
    page.write_text(page.read_text(encoding="utf-8") + "\n- 2026-10-10 — Clarified the category sentence.\n", encoding="utf-8")
    result = run_sync("--now", T3)
    assert result.returncode == 0, result.stdout + result.stderr
    meta = read_json(workspace / "export/meta.json")
    assert meta["generated_at"] == T3 and meta["last_synced_at"] == T3
    assert read_json(workspace / "export/bundle.json")["generated_at"] == T3


def test_previous_dir_can_differ_from_out(workspace: Path, run_sync):
    assert run_sync("--now", T1, out="first").returncode == 0
    result = run_sync("--now", T2, "--previous", "first", out="second")
    assert result.returncode == 0, result.stdout + result.stderr
    assert read_json(workspace / "second/meta.json")["generated_at"] == T1


def test_gap_tracker_columns_and_options_are_checked(workspace: Path, run_sync):
    tracker = workspace / "templates/databases/canon-gaps.csv"
    original = tracker.read_text(encoding="utf-8")

    # Wrong header.
    tracker.write_text(original.replace("Suggested page", "Page", 1), encoding="utf-8")
    result = run_sync("--now", T1)
    assert result.returncode == 1 and "gap tracker" in result.stderr and "columns" in result.stderr

    # Unknown Suggested page value.
    tracker.write_text(original.replace(",glossary,", ",no_such_page,", 1), encoding="utf-8")
    result = run_sync("--now", T1)
    assert result.returncode == 1 and "no_such_page" in result.stderr

    # Unknown Status value.
    tracker.write_text(original.replace(",patched,", ",done,", 1), encoding="utf-8")
    result = run_sync("--now", T1)
    assert result.returncode == 1 and "'done'" in result.stderr

    # The optional created-time column is accepted.
    lines = original.splitlines()
    lines[0] += ",Reported"
    lines[1:] = [line + ",2026-09-26T10:00:00Z" for line in lines[1:]]
    tracker.write_text("\n".join(lines) + "\n", encoding="utf-8")
    assert run_sync("--now", T1).returncode == 0

    # A Notion data source is skipped with a note instead of an error.
    contract = workspace / "templates/contracts/context-contract.yaml"
    contract.write_text(
        contract.read_text(encoding="utf-8").replace(
            "gap_tracker: templates/databases/canon-gaps.csv", 'gap_tracker: "collection://canon-gaps-data-source-id"'
        ),
        encoding="utf-8",
    )
    result = run_sync("--now", T1)
    assert result.returncode == 0 and "not checked" in result.stdout


def test_dry_run_writes_nothing(workspace: Path, run_sync):
    result = run_sync("--now", T1, "--dry-run")
    assert result.returncode == 0, result.stdout + result.stderr
    assert "would write" in result.stdout
    assert not (workspace / "export").exists()


def test_past_next_review_warns_and_fail_on_warn_fails(workspace: Path, run_sync):
    page = workspace / "templates/canon/icp_personas.md"
    page.write_text(page.read_text(encoding="utf-8").replace("next_review: 2027-01-08", "next_review: 2026-01-08", 1), encoding="utf-8")

    result = run_sync("--now", T1)
    assert result.returncode == 0, result.stdout + result.stderr
    warnings = read_json(workspace / "export/meta.json")["warnings"]
    assert any("icp_personas" in w and "next_review" in w for w in warnings), warnings

    assert run_sync("--now", T1, "--fail-on-warn").returncode == 1


def test_metric_restatement_warns(workspace: Path, run_sync):
    page = workspace / "templates/canon/positioning.md"
    page.write_text(
        page.read_text(encoding="utf-8") + "\n## Traction\n\nWe serve 400+ customers and passed $2M ARR last quarter, up 35%.\n",
        encoding="utf-8",
    )
    result = run_sync("--now", T1)
    assert result.returncode == 0, result.stdout + result.stderr
    warnings = read_json(workspace / "export/meta.json")["warnings"]
    assert any("positioning" in w and "metric" in w for w in warnings), warnings


def test_stale_canon_file_is_removed(workspace: Path, run_sync):
    stale = workspace / "export/canon/retired_page.md"
    stale.parent.mkdir(parents=True)
    stale.write_text("<!-- generated by canon-sync. old -->\n", encoding="utf-8")
    result = run_sync("--now", T1)
    assert result.returncode == 0, result.stdout + result.stderr
    assert not stale.exists()
    assert "removed" in result.stdout


def test_invalid_contract_is_rejected(workspace: Path, run_sync):
    contract = workspace / "templates/contracts/context-contract.yaml"
    contract.write_text(contract.read_text(encoding="utf-8").replace("status: grounded", "status: verified", 1), encoding="utf-8")
    result = run_sync("--now", T1)
    assert result.returncode == 1
    assert "contract" in result.stderr and "verified" in result.stderr
    assert not (workspace / "export").exists()


def test_help_explains_the_metric_heuristic(run_sync):
    result = run_sync("--help")
    assert result.returncode == 0
    assert "metric" in result.stdout and "percentage" in result.stdout and "Two clocks" in result.stdout
