#!/usr/bin/env python3
"""canon_sync: export the canon described by a context contract into a read-only mirror.

    python scripts/canon_sync.py --contract templates/contracts/context-contract.yaml --out export/

Reads the contract, fetches every canonical page through the adapter named by
`source_of_truth` (markdown | notion | confluence), validates, and writes:

    export/contract.yaml      verbatim copy of the contract file
    export/canon/<slug>.md    one file per page with the generated header
    export/meta.json          the two clocks and the manifest of the run
    export/bundle.json        everything in one file for single-fetch injection

Nothing is written when a validation gate fails (exit 1); the previous export
stays intact. With --dry-run the script reports what it would write and exits.
"""

from __future__ import annotations

import argparse
import csv
import datetime as dt
import hashlib
import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

# Make the sibling modules importable whether this file is run as a script
# (python scripts/canon_sync.py) or imported by the tests.
SCRIPTS_DIR = Path(__file__).resolve().parent
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

import validate_contract  # noqa: E402
from adapters.base import FetchedPage, SyncContext  # noqa: E402
from adapters.confluence import ConfluenceAdapter  # noqa: E402
from adapters.markdown import MarkdownAdapter  # noqa: E402
from adapters.notion import NotionAdapter, NotionError  # noqa: E402
from common import (  # noqa: E402
    CAVEATS,
    REPO_ROOT,
    iso_z,
    json_ready,
    load_schema,
    parse_iso_z,
    resolve_relative,
    schema_errors,
    to_date,
    utc_now,
)

EPILOG = """
Validation gates (exit 1, nothing written):
  - the contract does not parse, fails schemas/json/*.schema.json (when present)
    or fails the built-in structural checks
  - a canonical slug ends up with neither an export nor a pages_missing entry
  - a generated file lacks its header
  - a page whose contract status is `grounded` still contains [CONFIRM] or [YOU DECIDE]
  - a markdown page's frontmatter slug/status/owner disagrees with the contract
  - the gap tracker CSV (rules.gap_tracker) has unexpected columns, or a row's
    "Suggested page" / "Status" is not an allowed value
  - export/meta.json or export/bundle.json would not validate against their schemas

Warnings (listed in meta.json.warnings and printed; exit 1 only with --fail-on-warn):
  - a page could not be read and was exported as a placeholder
  - bundle.json is larger than 150 KiB (a canon that large is copying depth)
  - a page is past its next_review (frontmatter, else the contract's next_review)
  - a body line looks like it restates a metric value. The heuristic is deliberately
    simple: outside code fences and table rows, a line that contains a currency
    amount ($1,200 / 3,4 M EUR style), a percentage (12%), or the words
    "customers"/"logos"/"ARR"/"MRR" next to a number. Canon pages hold definitions
    and pull methods, never values; a hit means "look at this line", nothing more.

Two clocks:
  generated_at    advances only when the exported content changed (hash over every
                  page's slug, status and markdown plus the contract text). Unchanged
                  content keeps the previous export's value, so the mirror diff stays
                  empty and no pull request is opened.
  last_synced_at  advances on every successful run; it is the freshness heartbeat
                  that check_freshness.py reads.
"""

ADAPTERS = {
    "markdown": MarkdownAdapter,
    "notion": NotionAdapter,
    "confluence": ConfluenceAdapter,
}

HEADER_PREFIX = "<!-- generated by canon-sync."
MARKER_RE = re.compile(r"\[(CONFIRM|YOU DECIDE)\]")
BUNDLE_WARN_BYTES = 150 * 1024

# The metric heuristic described in EPILOG. Each pattern is (label, regex).
METRIC_PATTERNS = [
    ("currency amount", re.compile(r"[$€£]\s?\d[\d,]*(?:\.\d+)?(?:\s?(?:k|m|bn|b|mm))?\b", re.IGNORECASE)),
    ("percentage", re.compile(r"\b\d+(?:\.\d+)?\s?%")),
    (
        "metric word next to a number",
        re.compile(
            r"\b(?:ARR|MRR|customers?|logos)\b\W{0,3}\$?\d"  # "ARR of $4M", "customers: 400"
            r"|\b\d[\d,.]*\+?\s*(?:k|m)?\s+(?:customers|logos)\b",  # "400+ customers"
            re.IGNORECASE,
        ),
    ),
]

# The gap tracker (docs/formats.md section 6). "Reported" is a created-time column
# that a database fills automatically, so a CSV may or may not carry it.
GAP_TRACKER_COLUMNS = ["Gap", "Where it hurt", "Suggested page", "Status", "Reporter", "Context link"]
GAP_TRACKER_OPTIONAL_COLUMNS = ["Reported"]
GAP_STATUS_VALUES = ("new", "accepted", "patched", "rejected")
GAP_EXTRA_PAGE_VALUES = ("new_page", "decision_log", "unsure")


@dataclass
class SyncResult:
    """Everything one run decided, before anything touches the disk."""

    contract_path: Path
    out_dir: Path
    pages: list[FetchedPage] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    notes: list[str] = field(default_factory=list)
    generated_at: str = ""
    last_synced_at: str = ""
    content_hash: str = ""
    content_changed: bool = True
    change_reason: str = ""
    files: dict[str, bytes] = field(default_factory=dict)  # path relative to out_dir -> bytes
    stale_files: list[Path] = field(default_factory=list)  # existing canon files no longer in the contract
    meta: dict[str, Any] = field(default_factory=dict)
    bundle: dict[str, Any] = field(default_factory=dict)

    @property
    def ok(self) -> bool:
        return not self.errors


# --- Rendering ---------------------------------------------------------------------------


def render_header(url: str, slug: str, status: str, owner: str, generated_at: str, available: bool) -> str:
    """The generated header from docs/formats.md section 5, byte for byte."""
    tail = f"generated_at: {generated_at} | caveat: {CAVEATS[status]}"
    if not available:
        tail += " | available: false"
    return (
        "<!-- generated by canon-sync. DO NOT EDIT: edit the source page, the next sync overwrites this file.\n"
        f"source: {url} | slug: {slug} | status: {status} | owner: {owner}\n"
        f"{tail} -->"
    )


def render_page_file(page: FetchedPage, generated_at: str) -> str:
    header = render_header(page.url, page.slug, page.status, page.owner, generated_at, page.available)
    if not page.available:
        return header + "\n"
    return header + "\n" + page.document


# --- Checks on page bodies ------------------------------------------------------------------


def prose_lines(body: str) -> list[tuple[int, str]]:
    """(line_number, text) for body lines outside code fences and table rows."""
    result = []
    in_code = False
    for number, line in enumerate(body.splitlines(), start=1):
        stripped = line.strip()
        if stripped.startswith("```") or stripped.startswith("~~~"):
            in_code = not in_code
            continue
        if in_code or stripped.startswith("|"):
            continue
        result.append((number, line))
    return result


def marker_errors(page: FetchedPage) -> list[str]:
    """A grounded page may not carry an unresolved [CONFIRM] / [YOU DECIDE] marker."""
    if page.status != "grounded" or not page.available:
        return []
    found = []
    for number, line in enumerate(page.body.splitlines(), start=1):
        for match in MARKER_RE.finditer(line):
            found.append(f"{page.slug}: status is grounded but body line {number} contains {match.group(0)}")
    return found


def metric_warnings(page: FetchedPage) -> list[str]:
    """Lines that look like they restate a metric value (heuristic; see EPILOG)."""
    found = []
    for number, line in prose_lines(page.body):
        for label, pattern in METRIC_PATTERNS:
            match = pattern.search(line)
            if match:
                found.append(f"{page.slug}: line {number} may restate a metric value ({label}: {match.group(0).strip()!r})")
                break  # one warning per line is enough
    return found


def review_warning(page: FetchedPage, contract: dict[str, Any], today: dt.date) -> str | None:
    """Past next_review: the page's own frontmatter date, else the contract's."""
    due = page.next_review or to_date(contract.get("next_review"))
    if due is not None and due < today:
        source = "frontmatter" if page.next_review else "contract"
        return f"{page.slug}: past next_review {due.isoformat()} ({source}); owner {page.owner} should re-verify"
    return None


# --- Gap tracker -------------------------------------------------------------------------------


def check_gap_tracker(value: Any, slugs: list[str], base_dirs: list[Path]) -> tuple[list[str], list[str]]:
    """Verify the gap tracker CSV's columns and select options against the contract."""
    errors: list[str] = []
    notes: list[str] = []
    if not value or not isinstance(value, str):
        notes.append("gap tracker: not configured (rules.gap_tracker is empty)")
        return errors, notes
    if value.startswith("collection://"):
        notes.append("gap tracker: Notion data source; columns are not checked offline")
        return errors, notes
    if not value.lower().endswith(".csv"):
        notes.append(f"gap tracker: {value!r} is not a CSV path; not checked")
        return errors, notes

    path = resolve_relative(value, base_dirs)
    if not path.is_file():
        errors.append(f"gap tracker: {value} not found (looked at {path})")
        return errors, notes

    with open(path, "r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.reader(handle)
        try:
            header = next(reader)
        except StopIteration:
            errors.append(f"gap tracker: {path} is empty")
            return errors, notes
        header = [column.strip() for column in header]
        expected_prefix = header[: len(GAP_TRACKER_COLUMNS)]
        if expected_prefix != GAP_TRACKER_COLUMNS:
            errors.append(
                f"gap tracker: columns must start with {GAP_TRACKER_COLUMNS}, found {header} ({path})"
            )
            return errors, notes
        extra = [column for column in header[len(GAP_TRACKER_COLUMNS):] if column not in GAP_TRACKER_OPTIONAL_COLUMNS]
        if extra:
            errors.append(f"gap tracker: unexpected columns {extra}; only {GAP_TRACKER_OPTIONAL_COLUMNS} may follow the standard set")

        allowed_pages = set(slugs) | set(GAP_EXTRA_PAGE_VALUES)
        row_count = 0
        for row_number, row in enumerate(reader, start=2):
            if not any(cell.strip() for cell in row):
                continue
            row_count += 1
            record = dict(zip(header, row))
            page = record.get("Suggested page", "").strip()
            if page not in allowed_pages:
                errors.append(
                    f"gap tracker: row {row_number} Suggested page {page!r} is not a canonical slug or one of {', '.join(GAP_EXTRA_PAGE_VALUES)}"
                )
            status = record.get("Status", "").strip()
            if status not in GAP_STATUS_VALUES:
                errors.append(f"gap tracker: row {row_number} Status {status!r} is not one of {', '.join(GAP_STATUS_VALUES)}")
    notes.append(f"gap tracker: {path.name} columns and {row_count} row(s) checked")
    return errors, notes


# --- The two clocks -------------------------------------------------------------------------------


def compute_content_hash(pages: list[FetchedPage], contract_bytes: bytes) -> str:
    """sha256 over the sorted (slug, status, markdown) tuples plus the contract text."""
    digest = hashlib.sha256()
    for page in sorted(pages, key=lambda p: p.slug):
        digest.update(page.slug.encode("utf-8") + b"\0")
        digest.update(page.status.encode("utf-8") + b"\0")
        digest.update(page.document.encode("utf-8") + b"\0")
    digest.update(contract_bytes)
    return digest.hexdigest()


def read_previous(previous_dir: Path) -> tuple[str | None, str | None]:
    """generated_at from the previous bundle.json and content_hash from the previous meta.json."""
    generated_at = None
    content_hash = None
    bundle_path = previous_dir / "bundle.json"
    meta_path = previous_dir / "meta.json"
    try:
        if bundle_path.is_file():
            with open(bundle_path, "r", encoding="utf-8") as handle:
                generated_at = json.load(handle).get("generated_at")
        if meta_path.is_file():
            with open(meta_path, "r", encoding="utf-8") as handle:
                meta = json.load(handle)
            content_hash = meta.get("content_hash")
            generated_at = generated_at or meta.get("generated_at")
    except (OSError, ValueError, AttributeError):
        return None, None
    return generated_at, content_hash


# --- Build ------------------------------------------------------------------------------------------


def build(
    contract_path: Path,
    out_dir: Path,
    previous_dir: Path,
    source_root_override: str | None = None,
    now: dt.datetime | None = None,
) -> SyncResult:
    """Fetch, validate and render everything in memory. Writes nothing."""
    now = now or utc_now()
    result = SyncResult(contract_path=contract_path, out_dir=out_dir)

    # 1. Contract.
    try:
        contract_bytes = contract_path.read_bytes()
        contract = yaml.safe_load(contract_bytes.decode("utf-8"))
    except FileNotFoundError:
        result.errors.append(f"contract not found: {contract_path}")
        return result
    except (yaml.YAMLError, UnicodeDecodeError) as exc:
        result.errors.append(f"contract does not parse: {exc}")
        return result

    kind = validate_contract.detect_kind(contract)
    if kind not in (validate_contract.KIND_BUSINESS, validate_contract.KIND_CLIENT):
        result.errors.append("canon_sync needs a context contract with canonical_pages (business or client); this file is not one")
        return result
    errors, notes = validate_contract.validate_data(contract, kind)
    result.notes += [f"contract: {note}" for note in notes]
    if errors:
        result.errors += [f"contract: {error}" for error in errors]
        return result

    # 2. Adapter.
    source = contract["source_of_truth"]
    source_root = source_root_override or str(contract.get("source_root", ""))
    base_dirs = [REPO_ROOT, contract_path.resolve().parent]
    if source == "markdown":
        root_path = resolve_relative(source_root, base_dirs)
        if not root_path.is_dir():
            result.errors.append(f"source_root {source_root!r} is not a directory (looked at {root_path}); use --source-root to override")
            return result
        source_root = str(root_path)
    page_url_base = str(contract.get("page_url_base") or "")
    ctx = SyncContext(contract=contract, source_root=source_root, page_url_base=page_url_base, today=now.date())
    try:
        adapter = ADAPTERS[source](ctx)
    except NotImplementedError as exc:
        result.errors.append(str(exc))
        return result
    except NotionError as exc:
        result.errors.append(str(exc))
        return result

    # 3. Pages.
    slugs = list(contract["canonical_pages"].keys())
    for slug, entry in contract["canonical_pages"].items():
        try:
            page = adapter.fetch_page(slug, entry)
        except Exception as exc:  # a crash in one page must not hide the others
            page = FetchedPage(
                slug=slug,
                title=slug,
                status=str(entry.get("status", "")),
                owner=str(entry.get("owner") or entry.get("owner_role") or ""),
                review=str(entry.get("review", "")),
                url=page_url_base + str(entry.get("id", "")),
                available=False,
                problems=[f"{slug}: {exc.__class__.__name__}: {exc}"],
            )
        result.pages.append(page)
        result.errors += page.problems
        result.notes += page.notes
        if not page.available:
            if not page.problems:
                result.warnings.append(f"{slug}: page not available; exported as a placeholder (see pages_missing)")
            continue
        result.errors += marker_errors(page)
        warning = review_warning(page, contract, ctx.today)
        if warning:
            result.warnings.append(warning)
        result.warnings += metric_warnings(page)

    # 4. Gap tracker (business contracts carry rules.gap_tracker; client contracts may not).
    gap_errors, gap_notes = check_gap_tracker((contract.get("rules") or {}).get("gap_tracker"), slugs, base_dirs)
    result.errors += gap_errors
    result.notes += gap_notes

    if result.errors:
        return result

    # 5. The two clocks.
    result.content_hash = compute_content_hash(result.pages, contract_bytes)
    result.last_synced_at = iso_z(now)
    previous_generated_at, previous_hash = read_previous(previous_dir)
    if previous_generated_at and previous_hash == result.content_hash:
        result.generated_at = previous_generated_at
        result.content_changed = False
        result.change_reason = f"unchanged since {previous_generated_at}; kept generated_at"
    else:
        result.generated_at = result.last_synced_at
        result.content_changed = True
        if previous_hash is None:
            result.change_reason = "no previous export with a content hash; new generated_at"
        else:
            result.change_reason = "content changed since the previous export; new generated_at"
    if parse_iso_z(result.generated_at) > parse_iso_z(result.last_synced_at):
        # Clock skew between machines could do this; keeping the invariant matters more.
        result.generated_at = result.last_synced_at
        result.notes.append("previous generated_at was in the future; reset to now")

    # 6. Files.
    result.files["contract.yaml"] = contract_bytes
    pages_synced = []
    pages_missing = []
    bundle_pages: dict[str, Any] = {}
    for page in result.pages:
        text = render_page_file(page, result.generated_at)
        result.files[f"canon/{page.slug}.md"] = text.encode("utf-8")
        (pages_synced if page.available else pages_missing).append(page.slug)
        entry = contract["canonical_pages"][page.slug]
        bundle_page: dict[str, Any] = {
            "title": page.title or page.slug,
            "status": page.status,
            "owner": page.owner,
            "review": page.review,
            "url": page.url,
            "available": page.available,
            "markdown": text if page.available else "",
            "caveat": CAVEATS[page.status],
            "source_id": str(entry.get("id", "")),
        }
        visibility = entry.get("visibility") or contract.get("visibility") or contract.get("default_visibility")
        if visibility:
            bundle_page["visibility"] = visibility
        if page.next_review:
            bundle_page["next_review"] = page.next_review.isoformat()
        bundle_pages[page.slug] = bundle_page

    # The bundle carries only content-derived fields (no last_synced_at), so an
    # unchanged canon produces a byte-identical bundle.json and the nightly diff
    # is limited to meta.json's heartbeat.
    result.bundle = {
        "generated_at": result.generated_at,
        "contract_version": contract["contract_version"],
        "source_of_truth": source,
        "content_hash": result.content_hash,
        "contract": json_ready(contract),
        "pages": bundle_pages,
    }
    bundle_text = json.dumps(result.bundle, indent=2, ensure_ascii=False) + "\n"
    bundle_bytes = bundle_text.encode("utf-8")
    if len(bundle_bytes) > BUNDLE_WARN_BYTES:
        result.warnings.append(f"bundle.json is {len(bundle_bytes)} bytes, over the {BUNDLE_WARN_BYTES} byte guideline; canon should point to depth, not copy it")

    result.meta = {
        "generated_at": result.generated_at,
        "last_synced_at": result.last_synced_at,
        "contract_version": contract["contract_version"],
        "source_of_truth": source,
        "pages_synced": pages_synced,
        "pages_missing": pages_missing,
        "bundle_bytes": len(bundle_bytes),
        "validation": "passed",
        "warnings": list(result.warnings),
        "content_hash": result.content_hash,
    }
    result.files["bundle.json"] = bundle_bytes
    result.files["meta.json"] = (json.dumps(result.meta, indent=2, ensure_ascii=False) + "\n").encode("utf-8")

    # 7. Gates on the artifacts themselves.
    for slug in slugs:
        if slug not in pages_synced and slug not in pages_missing:
            result.errors.append(f"{slug}: neither exported nor listed in pages_missing")
    for relative, data in result.files.items():
        if relative.startswith("canon/") and not data.startswith(HEADER_PREFIX.encode("utf-8")):
            result.errors.append(f"{relative}: generated file lacks its header")
    for schema_name, instance in (("meta.schema.json", result.meta), ("bundle.schema.json", result.bundle)):
        schema = load_schema(schema_name)
        if schema is None:
            result.notes.append(f"schemas/json/{schema_name} not present; artifact not schema-checked")
        else:
            result.errors += schema_errors(instance, schema, label=f"export {schema_name}")

    # 8. Files in out/canon that no longer belong to a canonical slug.
    canon_dir = out_dir / "canon"
    if canon_dir.is_dir():
        for existing in sorted(canon_dir.glob("*.md")):
            if existing.stem not in slugs:
                result.stale_files.append(existing)
    return result


# --- Write and report ----------------------------------------------------------------------------------


def write(result: SyncResult) -> None:
    """Write every artifact and remove stale canon files. Call only when result.ok."""
    (result.out_dir / "canon").mkdir(parents=True, exist_ok=True)
    for relative, data in result.files.items():
        target = result.out_dir / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)
    for stale in result.stale_files:
        stale.unlink()


def verify_export_dir(out_dir: Path, slugs: list[str]) -> list[str]:
    """Re-read the written mirror and check the gates that can be checked from disk."""
    problems = []
    for slug in slugs:
        path = out_dir / "canon" / f"{slug}.md"
        if not path.is_file():
            problems.append(f"{path} was not written")
            continue
        with open(path, "r", encoding="utf-8") as handle:
            if not handle.read(len(HEADER_PREFIX)) == HEADER_PREFIX:
                problems.append(f"{path} lacks its header")
    for name in ("contract.yaml", "meta.json", "bundle.json"):
        if not (out_dir / name).is_file():
            problems.append(f"{out_dir / name} was not written")
    return problems


def print_summary(result: SyncResult, dry_run: bool, fail_on_warn: bool) -> None:
    for note in result.notes:
        print(f"note: {note}")
    for warning in result.warnings:
        print(f"WARNING: {warning}")
    for error in result.errors:
        print(f"ERROR: {error}", file=sys.stderr)

    synced = [page.slug for page in result.pages if page.available]
    missing = [page.slug for page in result.pages if not page.available]
    print()
    if result.errors:
        print(f"canon-sync FAILED: {len(result.errors)} error(s); nothing written")
        return
    status = "DRY RUN" if dry_run else "OK"
    if fail_on_warn and result.warnings:
        status = "FAILED (--fail-on-warn)"
    print(f"canon-sync {status}: {len(synced)} page(s) synced, {len(missing)} missing, {len(result.warnings)} warning(s)")
    version = result.meta.get("contract_version", "?")
    print(f"  contract        {result.contract_path} (version {version}, source {result.meta.get('source_of_truth', '?')})")
    print(f"  pages synced    {', '.join(synced) or '-'}")
    print(f"  pages missing   {', '.join(missing) or '-'}")
    print(f"  generated_at    {result.generated_at}  ({result.change_reason})")
    print(f"  last_synced_at  {result.last_synced_at}")
    print(f"  bundle          {result.meta.get('bundle_bytes', 0)} bytes")
    total = sum(len(data) for data in result.files.values())
    if dry_run:
        print(f"  would write     {len(result.files)} file(s), {total} bytes, to {result.out_dir}/")
        for relative, data in result.files.items():
            print(f"                  {relative} ({len(data)} bytes)")
        for stale in result.stale_files:
            print(f"  would remove    {stale}")
    else:
        print(f"  wrote           {len(result.files)} file(s), {total} bytes, to {result.out_dir}/")
        for stale in result.stale_files:
            print(f"  removed         {stale}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, epilog=EPILOG, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--contract", required=True, help="path to the context contract YAML")
    parser.add_argument("--out", default="export", help="output directory (default: export/)")
    parser.add_argument("--source-root", help="override the contract's source_root (vault folder for markdown)")
    parser.add_argument("--previous", help="directory holding the previous export for the two-clocks comparison (default: --out)")
    parser.add_argument("--dry-run", action="store_true", help="validate and report; write nothing")
    parser.add_argument("--fail-on-warn", action="store_true", help="exit 1 when there are warnings")
    parser.add_argument("--now", help="ISO 8601 UTC timestamp to use as the run time (tests, reproducible builds)")
    args = parser.parse_args(argv)

    now = parse_iso_z(args.now) if args.now else None
    out_dir = Path(args.out)
    previous_dir = Path(args.previous) if args.previous else out_dir

    result = build(Path(args.contract), out_dir, previous_dir, args.source_root, now)
    if not result.ok:
        print_summary(result, args.dry_run, args.fail_on_warn)
        return 1
    if not args.dry_run:
        write(result)
        problems = verify_export_dir(out_dir, [page.slug for page in result.pages])
        if problems:
            result.errors += problems
            print_summary(result, args.dry_run, args.fail_on_warn)
            return 1
    print_summary(result, args.dry_run, args.fail_on_warn)
    if args.fail_on_warn and result.warnings:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
